-- MySQL Script generated by MySQL Workbench
-- Thu Jun 11 23:47:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema my_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema my_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_app` DEFAULT CHARACTER SET utf8 ;
USE `my_app` ;

-- -----------------------------------------------------
-- Table `my_app`.`science`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_app`.`science` (
  `cid` INT(11) NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(150) NOT NULL,
  `date` DATETIME NOT NULL,
  `news` TEXT NOT NULL,
  PRIMARY KEY (`cid`))
ENGINE = MyISAM
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `my_app`.`sport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_app`.`sport` (
  `cid` INT(11) NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(150) NOT NULL,
  `date` DATETIME NOT NULL,
  `news` TEXT NOT NULL,
  PRIMARY KEY (`cid`))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `my_app`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_app`.`news` (
  `cdi` INT(11) NOT NULL,
  `uid` VARCHAR(200) NOT NULL,
  `news` TEXT NOT NULL,
  `science_cid` INT(11) NOT NULL,
  `sport_cid` INT(11) NOT NULL,
  PRIMARY KEY (`cdi`, `science_cid`, `sport_cid`),
  INDEX `fk_news_science1_idx` (`science_cid` ASC) VISIBLE,
  INDEX `fk_news_sport1_idx` (`sport_cid` ASC) VISIBLE,
  CONSTRAINT `fk_news_science1`
    FOREIGN KEY (`science_cid`)
    REFERENCES `my_app`.`science` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_news_sport1`
    FOREIGN KEY (`sport_cid`)
    REFERENCES `my_app`.`sport` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `my_app`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_app`.`comment` (
  `cid` INT(11) NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(150) NOT NULL,
  `date` DATETIME NOT NULL,
  `message` TEXT NOT NULL,
  `news_cdi` INT(11) NOT NULL,
  PRIMARY KEY (`cid`, `news_cdi`),
  INDEX `fk_comment_news1_idx` (`news_cdi` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `my_app`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_app`.`users` (
  `ID_Users` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `comment_cid` INT(11) NOT NULL,
  PRIMARY KEY (`ID_Users`, `comment_cid`),
  INDEX `fk_users_comment_idx` (`comment_cid` ASC) VISIBLE,
  CONSTRAINT `fk_users_comment`
    FOREIGN KEY (`comment_cid`)
    REFERENCES `my_app`.`comment` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `my_app`.`politics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_app`.`politics` (
  `cid` INT(11) NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(150) NOT NULL,
  `date` DATETIME NOT NULL,
  `news` TEXT NOT NULL,
  `sport_cid` INT(11) NOT NULL,
  PRIMARY KEY (`cid`, `sport_cid`),
  INDEX `fk_politics_sport1_idx` (`sport_cid` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
